# Generated by Django 4.2.2 on 2023-09-02 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_remove_user_user_name_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="listitem",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
